//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.repos.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pageroleaction
    {
        public int id { get; set; }
        public int id_pagerole { get; set; }
        public short id_action { get; set; }
    
        public virtual action action { get; set; }
        public virtual pagerole pagerole { get; set; }
    }
}
