//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.repos.MSSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class parameterContext : DbContext
    {
        public parameterContext()
            : base("name=parameterContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<page> page { get; set; }
        public virtual DbSet<pagerole> pagerole { get; set; }
        public virtual DbSet<action> action { get; set; }
        public virtual DbSet<pageroleaction> pageroleaction { get; set; }
    
        public virtual ObjectResult<getpages_Result> getpages(Nullable<System.Guid> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getpages_Result>("getpages", uidParameter);
        }
    
        public virtual ObjectResult<getpagesbyrole_Result> getpagesbyrole(Nullable<System.Guid> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getpagesbyrole_Result>("getpagesbyrole", uidParameter);
        }
    }
}
