//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.globalization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class commonres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal commonres() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("core.globalization.commonres", typeof(commonres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos..
        /// </summary>
        public static string credentials_invalid {
            get {
                return ResourceManager.GetString("credentials_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado correctamente.
        /// </summary>
        public static string delete_succesful {
            get {
                return ResourceManager.GetString("delete_succesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro no encontrado.
        /// </summary>
        public static string register_not_found {
            get {
                return ResourceManager.GetString("register_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado correctamente.
        /// </summary>
        public static string save_succesful {
            get {
                return ResourceManager.GetString("save_succesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error no identificado.
        /// </summary>
        public static string unknown_erro {
            get {
                return ResourceManager.GetString("unknown_erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizado correctamente.
        /// </summary>
        public static string update_succesful {
            get {
                return ResourceManager.GetString("update_succesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ya se encuentra registrado.
        /// </summary>
        public static string user_exists {
            get {
                return ResourceManager.GetString("user_exists", resourceCulture);
            }
        }
    }
}
